.eslintrc.js, head.html, scripts/filter.js, scripts/martech.js, scripts/scripts.js, test/utils.js
- introduce js modules
- fixed linting
=> refactor: modularization & linting

tools/templates/picker.html
=> feat(picker): Display Premium templates

tools/templates/picker.html
- Load all templates given by the API
- Optimise assets on the page
- Support for `q` query parameter
=> feat(templates): Picker improvements

express/blocks/pricing/pricing.css, express/blocks/pricing/pricing.js
Pricing page header for desktop only with animation.
=> feat(pricing): header

.github/workflows/run-tests.yaml, express/blocks/blog-posts/blog-posts.js, express/scripts/martech.js, express/scripts/scripts.js
=> feat(ci): Enable linting check for each commit

helix-query.yaml
Update index based on latest content structure and extract from metadata.
@dominique-pfister Is there a way to test the result of this new index definition on some files ?
=> feat(index): compute from meta

helix-query.yaml
Just adding the last modified on all indexes so that we have it
=> feat(index): Index the last modified date

express/blocks/tutorials/tutorials.js, express/scripts/scripts.js
- use "[Test]" in content
- create a section with h3 "Test" and other content
- marker will be replaced with fragment content
=> feat: fragments

express/blocks/template-list/template-list.js, express/blocks/tutorials/tutorials.js, test/unit/blocks/blocks-test-list.js, test/unit/blocks/expected/template-list.linkedimage.block.html, test/unit/blocks/expected/template-list.linknotext.block.html, test/unit/blocks/expected/template-list.linkwithtext.block.html, test/unit/blocks/expected/template-list.video.block.html, test/unit/blocks/input/template-list.linkedimage.doc.html, test/unit/blocks/input/template-list.linknotext.doc.html, test/unit/blocks/input/template-list.linkwithtext.doc.html, test/unit/blocks/input/template-list.video.doc.html
=> fix(template-list): fix edge case and added tests

express/blocks/columns/columns.css, express/blocks/columns/columns.js, test/unit/blocks/blocks-test-list.js, test/unit/blocks/expected/columns.singlerow.block.html, test/unit/blocks/expected/columns.table.3.block.html, test/unit/blocks/expected/columns.table.numbered.10.block.html, test/unit/blocks/expected/columns.table.numbered.3.block.html, test/unit/blocks/input/columns.singlerow.doc.html, test/unit/blocks/input/columns.table.3.doc.html, test/unit/blocks/input/columns.table.numbered.10.doc.html, test/unit/blocks/input/columns.table.numbered.3.doc.html
=> feat: numbered columns

helix-query.yaml
=> Add short title to index

express/blocks/pricing/pricing.js, express/scripts/martech.js, tools/templates/picker.html
I'm adding Adobe Analytics instrumentation to many of the pages.
None
Adobe Analytics will allow us to be able to integrate with the 
I tested locally.  I used the Experience Cloud Debugger and my Chrome Network tools to ensure that analytics was flowing as expected.
=> Integrating Adobe Analytics

express/blocks/blog-posts/blog-posts.css, express/blocks/blog-posts/blog-posts.js, express/styles/styles.css
use better contrast for eyebrow
fixes #34 
> make sure keyboard indicator (focus) is always visible
I guess this depends on the embeds. currently the links below the images are focussed.
> better alt-texts for images
this is an authoring problem
=> fix(a11y): use better contrast for eyebrow in blogpost

express/blocks/pricing-plan/pricing-plan.css, express/blocks/pricing-plan/pricing-plan.js
Created the pricing-plan block for the individual-plan page
=> feature: pricing-plan block with colorful border gradient

express/blocks/template-list/template-list.js, test/unit/blocks/expected/template-list.linkedimage.block.html, test/unit/blocks/expected/template-list.linknotext.block.html
always add template class
- https://fix-template-no-link--spark-website--adobe.hlx.page/express/feature/image/remove-background
- https://fix-template-no-link--spark-website--adobe.hlx.page/drafts/yge/EN/images/resize
- https://fix-template-no-link--spark-website--adobe.hlx.page/express/feature/image/change-background-color
- https://fix-template-no-link--spark-website--adobe.hlx.page/express/create/video
=> fix(template): always add template class

express/blocks/faq/faq.css, express/blocks/list/list.css, express/blocks/list/list.js, express/blocks/pricing-plan/pricing-plan.css, express/blocks/pricing-plan/pricing-plan.js
- Fixed the margin of the FAQ block
- Fixed the console log errors in the list block when there is only 1 column
- Fixed the margins of the list block when there is only 1 column
- William did some analytics fixes
=> Individual Plan page margin fixes, list block console error fixes, william analytics fixes

express/blocks/list/list.js, express/blocks/pricing/pricing.js, express/blocks/template-list/template-list.js, express/scripts/scripts.js
=> fix(template-list): apply the webpPolyfill to loaded blueprint

express/blocks/template-list/template-list.css, express/scripts/scripts.js
Fix https://github.com/adobe/spark-website-issues/issues/21
=> feat(template-list): optional 4 column layout

.circleci/config.yml, .monitoring/homepage-pricing.js
Fix https://github.com/adobe/spark-website-issues/issues/33
=> feat(monitoring): set up production monitor

express/scripts/scripts.js
update to the helix-env
testing URLs...
https://helix-env-update--spark-website--adobe.hlx.page/express/pricing?helix-env=stage
https://helix-env-update--spark-website--adobe.hlx.page/express/pricing?helix-env=prod
https://helix-env-update--spark-website--adobe.hlx.page/express/pricing?helix-env=
see "buy now" and "login urls"
=> feat: update helix-env (guards, session scope, referrer)

express/blocks/template-list/template-list.js
quick fix for template inheritance with new structure without hero image.
=> fix(template-list): better guard for hero inheritance

express/scripts/martech.js
https://github.com/adobe/spark-website-issues/issues/22
- Before: https://www.adobe.com/express/create/logo
- After: https://issue-22--spark-website--adobe.hlx.page/express/create/logo
=> fix(cta): use cta in first section (hero or not)

express/scripts/martech.js
Fix https://github.com/adobe/spark-website-issues/issues/37
=> fix(region-picker): js error on preview and live

express/scripts/martech.js
Fix https://github.com/adobe/spark-website-issues/issues/36
=> fix(martech): add check if close button exists

express/scripts/scripts.js
=> fix: referrer handling typo

helix-query.yaml
adds a templates index, for english tree, only, for now
=> fix: add templates index

helix-query.yaml
=> fix: add robots column

express/scripts/martech.js, express/scripts/scripts.js
enable the body hide of AT for situations where martech is rushed.
https://target-hide-body--spark-website--adobe.hlx.page/express/pricing
=> feat(martech): hide body on martech rush

helix-query.yaml
overlapping indices cause issues (for now)
=> fix: disable templates temporarily

express/blocks/hero-animation/hero-animation.css, express/blocks/hero-animation/hero-animation.js
initial hero animation block
https://block-hero-animation--spark-website--adobe.hlx.page/drafts/uncled/hero-animation
=> feat(block): hero animation

express/blocks/hero-animation/hero-animation.css, express/blocks/hero-animation/hero-animation.js, express/styles/styles.css
some tune-up for the hero animation...
initial hero animation block
https://block-hero-animation--spark-website--adobe.hlx.page/drafts/uncled/hero-animation
=> hero-animation: styling and CLS

express/scripts/scripts.js
=> fix: block without block name fails

express/scripts/scripts.js
=> chore: add spark stage and qa

tools/sidekick/plugins.js
Fix https://github.com/adobe/express-website-issues/issues/125
=> feat: use dual hlx2/hlx3 publish action in sidekick

express/scripts/martech.js, express/styles/styles.css
https://gnav-smooth-replace--spark-website--adobe.hlx.page/express/
=> fix: better placeholder to gnav transition

express/blocks/blog-posts/blog-posts.js
https://block-blog-posts--spark-website--adobe.hlx.page/drafts/uncled/blog/category/education
=> fix(blog-posts): add category

express/blocks/pricing/pricing.js
https://pricing-sheet-fetch--spark-website--adobe.hlx.page/express/pricing
=> chore(pricing): update to hlx3 multisheet logic

express/blocks/columns/columns.js, helix-version.txt
This is making sure these pages look identical with `breaking-202106` (https://github.com/adobe/helix-word2md/issues/662):
- https://cell-alignment-test--spark-website--adobe.hlx.page/marketing/frictionless-resize
- https://main--spark-website--adobe.hlx.page/marketing/frictionless-resize
=> Cell alignment test

.github/workflows/purge-code.yaml
=> chore: use hlx3 branch of purge-code action

express/scripts/scripts.js, express/styles/lazy-styles.css, express/styles/styles.css, head.html
some more fine-tuning to get us back to hopefully 100.
funny enough it looks like we already get there on `hlx3.page` even without h2 push or any caching if martech is off:
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flighthouse-finetuning--spark-website--adobe.hlx3.page%2Fexpress%2Fcreate%2Fthumbnail%2Fyoutube%3Fmartech%3Doff
...and even with martech back turned on we get to 97...
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flighthouse-finetuning--spark-website--adobe.hlx3.page%2Fexpress%2Fcreate%2Fthumbnail%2Fyoutube
https://lighthouse-finetuning--spark-website--adobe.hlx.page/express/create/thumbnail/youtube
=> Lighthouse finetuning

express/scripts/scripts.js, express/styles/styles.css
hopefully this would improve the FCP
=> fix: FCP testing

tools/sidekick/config.js, tools/sidekick/plugins.js
Fix https://github.com/adobe/express-website-issues/issues/140
=> fix: always use innerHost for tools

tools/sidekick/config.js
Prep for https://github.com/adobe/helix-sidekick/issues/29
=> chore(sidekick): ensure outerHost contains no branch

express/scripts/martech.js
=> fix(analytics): bug where ctaPressed was not registered

express/scripts/martech.js
PR for the following issues:
Fix https://github.com/adobe/express-website-issues/issues/152
Fix https://github.com/adobe/express-website-issues/issues/153
Fix https://github.com/adobe/express-website-issues/issues/154
Fix https://github.com/adobe/express-website-issues/issues/155
Fix https://github.com/adobe/express-website-issues/issues/156
For the Spark website.
=> 152 to 155 analytics

express/scripts/martech.js, helix-query.yaml, package-lock.json
use simpler target names (without share :r :x and query string)
=> Simple targets

express/sitemap.xml
Fix adobe/express-website-issues#170
=> feat(seo): move sitemap.xml back to github

express/scripts/martech.js
this should enable rum collection for the spark-website
https://rum-collection--spark-website--adobe.hlx3.page/express/
=> feat(rum): enable rum collection

express/scripts/martech.js
adding explicit referrer...
https://rum-collection--spark-website--adobe.hlx3.page/express/?cwv=on
=> chore: add explicit referrer

express/blocks/columns/columns.css, express/blocks/columns/columns.js, express/scripts/scripts.js
Fix https://github.com/adobe/express-website-issues/issues/178
Test page: https://issue-178--spark-website--adobe.hlx3.page/drafts/rofe/fullsize
=> feat(columns): fullsize option

express/blocks/link-list/link-list.css, express/blocks/link-list/link-list.js, express/blocks/shared/carousel.js, express/scripts/scripts.js
Fix https://github.com/adobe/express-website-issues/issues/180
Test: https://issue-180--spark-website--adobe.hlx3.page/documentation/block-inventory#link-list
=> feat: new link-list block

express/scripts/martech.js, express/scripts/scripts.js
https://rum-collection-test--spark-website--adobe.hlx3.page/express/learn/blog?cwv=on
=> rum collection test

express/blocks/how-to-steps-carousel/how-to-steps-carousel.css, express/blocks/how-to-steps-carousel/how-to-steps-carousel.js
Fix: https://github.com/adobe/express-website-issues/issues/181
Test page: https://how-to-steps-carousel--spark-website--adobe.hlx3.page/documentation/block-inventory#how-to-make-something
=> feat: how-to-steps-carousel

express/scripts/martech.js, express/scripts/scripts.js
to suppress content flashes using the `at-body-style`.
see:
https://hide-content--spark-website--adobe.hlx3.page/express/
=> fix: custom content hiding

express/scripts/scripts.js, express/styles/styles.css
Added missing icons to sprite symbol list.
=> chore: missing icon symbols

express/blocks/new-banner/new-banner.css, express/blocks/new-banner/new-banner.js, test/unit/blocks/blocks-test-list.js, test/unit/blocks/expected/new-banner.h2.block.html, test/unit/blocks/expected/new-banner.h2.button.block.html, test/unit/blocks/expected/new-banner.h3.block.html, test/unit/blocks/input/new-banner.button.doc.html, test/unit/blocks/input/new-banner.h1.doc.html, test/unit/blocks/input/new-banner.h2.doc.html, test/unit/blocks/input/new-banner.h3.doc.html, test/unit/blocks/input/new-banner.h4.doc.html
Fix https://github.com/adobe/express-website-issues/issues/185
=> feat: new banner block

express/blocks/link-list/link-list.js
See https://github.com/adobe/spark-website/pull/196#discussion_r713795303
=> fix(link-list): remove primary class from buttons

express/blocks/template-list/template-list.js, express/styles/styles.css
https://column-bug--spark-website--adobe.hlx.live/express/create/flyer
=> Fix: Layout issue with columns

express/blocks/template-list/template-list.js
https://template-list-block--spark-website--adobe.hlx3.page/express/create/advertisement
https://template-list-block--spark-website--adobe.hlx3.page/express/create/post/instagram
vs. 
https://main--spark-website--adobe.hlx3.page/express/create/advertisement
https://main--spark-website--adobe.hlx3.page/express/create/post/instagram
=> chore: fix video height

express/scripts/scripts.js
https://how-to-carousel-block--spark-website--adobe.hlx3.page/express/create/spotlight/flyer-t2
vs.
https://main--spark-website--adobe.hlx3.page/express/create/spotlight/flyer-t2
=> how-to-carousel block regression

express/blocks/link-list/link-list.css
=> fix(link-list): regression from #209

helix-query.yaml
make target relative (less error-prone and easier to copy)
=> fix: use relative target
